SalesManagementSystemApp/urls.py
"""Routes for Pipeline Staging Sales Management System """
from django.urls import path
from . import views
app_name = 'SalesManagementSystemApp'
urlpatterns = [
    path('', views.HomePageMethod,name='Home'),
    path('admin/',views.AdminPageMethod,name='Admin'),
    path('SalesManagementSystemApp/Home/About', views.AboutPageMethod,
    name='About'),
    path('SalesManagementSystemApp/Home/AdminAbout',
    views.AdminAboutPageMethod,name='AdminAbout'),
    path('SalesManagementSystemApp/Home/AdminSignOut',
    views.AdminSignOutPageMethod,name='AdminSignOut'),
    path('SalesManagementSystemApp/Home/AdminSignIn/',views.AdminSignInMethod,
    name='AdminSignInPage'),
    path('SalesManagementSystemApp/Home/AdminCustomerSignIn/',
    views.AdminCustomerSignInMethod,name='AdminCustomerSignInPage'),
    path('SalesManagementSystemApp/Home/AdminCustomer/',
    views.AdminCustomerFormMethod,name='AdminCustomerInsertPage'),
    path('SalesManagementSystemApp/Home/AdminCustomerList/',
    views.AdminCustomerListMethod,name='AdminCustomerListPage'),
    path('SalesManagementSystemApp/Home/UpdateAdminCustomer/<int:id>/',
    views.AdminCustomerFormMethod,name='AdminCustomerUpdatePage'),
    path('SalesManagementSystemApp/Home/DeleteAdminCustomer/<int:id>/',
    views.AdminCustomerDelete,name='AdminCustomerDeletePage'),
    path('SalesManagementSystemApp/KeyPriorities/signup',
    views.CustomerSignUp,name='SignUp'),
    path('SalesManagementSystemApp/KeyPriorities/signin',
    views.CustomerSignIn, name='SignIn'),
    path('SalesManagementSystemApp/KeyPriorities/signout/',
    views.CustomerSignOut,name='SignOut'),
    path('SalesManagementSystemApp/KeyPriorities/<str:username>/<str:company_name>/',
    views.KeyPrioritiesMethod,name='KeyPriorities'),
    path('SalesManagementSystemApp/KeyPriorities/HR/<str:username>/<str:company_name>/',
    views.HRMethod,name='HR'),
    path('SalesManagementSystemApp/KeyPriorities/HR/<str:username>/<str:company_name>/GenerateStagePDF/',
    views.HRTableGenerate_PDF,name='HRTableGenerate_PDF'),
    path('SalesManagementSystemApp/KeyPriorities/HR/<str:username>/<str:company_name>/AddStageTable/',
    views.HRTableInsertStage,name='HRTableInsertStage'),
    path('SalesManagementSystemApp/KeyPriorities/HR/<str:username>/<str:company_name>/UpdateStageTable/<int:id>/',
    views.HRTableUpdateStage,name='HRTableUpdateStage'),
    path('SalesManagementSystemApp/KeyPriorities/HR/<str:username>/<str:company_name>/DeleteStageTable/<int:id>/<str:stage_name>/',
    views.HRTableDeleteStage,name='HRTableDeleteStage'),
    path('SalesManagementSystemApp/KeyPriorities/CustService/<str:username>/<str:company_name>/',
    views.CustServiceMethod,name ='CustService'),
    path('SalesManagementSystemApp/KeyPriorities/CustService/<str:username>/<str:company_name>/GenerateStagePDF/',
    views.CustServiceTableGenerate_PDF,name='CustServiceTableGenerate_PDF'),
    path('SalesManagementSystemApp/KeyPriorities/CustService/<str:username>/<str:company_name>/AddStageTable',
    views.CustServiceTableInsertStage,name='CustServiceTableInsertStage'),
    path('SalesManagementSystemApp/KeyPriorities/CustService/<str:username>/<str:company_name>/UpdateStageTable/<int:id>/',
    views.CustServiceTableUpdateStage,name='CustServiceTableUpdateStage'),
    path('SalesManagementSystemApp/KeyPriorities/CustService/<str:username>/<str:company_name>/DeleteStageTable/<int:id>/<str:stage_name>/',
    views.CustServiceTableDeleteStage,name='CustServiceTableDeleteStage'),
    path('SalesManagementSystemApp/KeyPriorities/IT/<str:username>/<str:company_name>/',
    views.ITMethod,name='IT'),
    path('SalesManagementSystemApp/KeyPriorities/IT/<str:username>/<str:company_name>/GenerateStagePDF/',
    views.ITTableGenerate_PDF,name='ITTableGenerate_PDF'),
    path('SalesManagementSystemApp/KeyPriorities/IT/<str:username>/<str:company_name>/AddStageTable',
    views.ITTableInsertStage,name='ITTableInsertStage'),
    path('SalesManagementSystemApp/KeyPriorities/IT/<str:username>/<str:company_name>/UpdateStageTable/<int:id>/',
    views.ITTableUpdateStage,name='ITTableUpdateStage'),
    path('SalesManagementSystemApp/KeyPriorities/IT/<str:username>/<str:company_name>/DeleteStageTable/<int:id>/<str:stage_name>/',
    views.ITTableDeleteStage,name='ITTableDeleteStage'),
    path('SalesManagementSystemApp/KeyPriorities/Sales/<str:username>/<str:company_name>/',
    views.SalesMethod,name='Sales'),
    path('SalesManagementSystemApp/KeyPriorities/Sales/<str:username>/<str:company_name>/GenerateStagePDF/',
    views.SalesTableGenerate_PDF,name='SalesTableGenerate_PDF'),
    path('SalesManagementSystemApp/KeyPriorities/Sales/<str:username>/<str:company_name>/AddStageTable',
    views.SalesTableInsertStage,name='SalesTableInsertStage'),
    path('SalesManagementSystemApp/KeyPriorities/Sales/<str:username>/<str:company_name>/UpdateStageTable/<int:id>/',
    views.SalesTableUpdateStage,name='SalesTableUpdateStage'),
    path('SalesManagementSystemApp/KeyPriorities/Sales/<str:username>/<str:company_name>/DeleteStageTable/<int:id>/<str:stage_name>/',
    views.SalesTableDeleteStage,name='SalesTableDeleteStage'),
    path('SalesManagementSystemApp/KeyPriorities/RD/<str:username>/<str:company_name>/',
    views.RDMethod,name='RD'),
    path('SalesManagementSystemApp/KeyPriorities/RD/<str:username>/<str:company_name>/GenerateStagePDF/',
    views.RDTableGenerate_PDF,name='RDTableGenerate_PDF'),
    path('SalesManagementSystemApp/KeyPriorities/RD/<str:username>/<str:company_name>/AddStageTable',
    views.RDTableInsertStage,name='RDTableInsertStage'),
    path('SalesManagementSystemApp/KeyPriorities/RD/<str:username>/<str:company_name>/UpdateStageTable/<int:id>/',
    views.RDTableUpdateStage,name='RDTableUpdateStage'),
    path('SalesManagementSystemApp/KeyPriorities/RD/<str:username>/<str:company_name>/DeleteStageTable/<int:id>/<str:stage_name>/',
    views.RDTableDeleteStage, name = 'RDTableDeleteStage'),
]

SalesManagementSystemProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SalesManagementSystemApp.urls')),
]

SalesManagementSystemApp/models.py
"""Form for Customer, Admin and Stage Models"""
from django.db import models
class Customer(models.Model):
    """Model for Customer Class"""
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30)
    company_name = models.CharField(max_length=15)
    password1 = models.CharField(max_length=20)
    password2 = models.CharField(max_length=20)
    def __str__(self):
        return self.username
class Admin(models.Model):
    """Model for Admin class"""
    username = models.CharField(max_length=150)
    password = models.CharField(max_length=150)
    def __str__(self):
        return str(self.username)
class Stage(models.Model):
    """Model for Stage Class"""
    custom_stage = models.CharField(max_length=150)
    def __str__(self):
        return str(self.custom_stage)
class CustServiceStage(models.Model):
    """Model for Cust Service Class"""
    custom_stage = models.CharField(max_length=150)
    def __str__(self):
        return str(self.custom_stage)
class ITStage(models.Model):
    """Model for IT Stage Class"""
    custom_stage = models.CharField(max_length=150)
    def __str__(self):
        return str(self.custom_stage)
class SalesStage(models.Model):
    """Model for Sales Stage Class"""
    custom_stage = models.CharField(max_length=150)
    def __str__(self):
        return str(self.custom_stage)
class RDStage(models.Model):
    """Model for R&D Stage Class"""
    custom_stage = models.CharField(max_length=150)
    def __str__(self):
        return str(self.custom_stage)
        

SalesManagementSystemApp/views.py
"""Views for Pipeline Staging Sales Management System"""
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from xhtml2pdf import pisa
from django.template import loader
from django.template.loader import get_template
from pipeline_staging_properties_pkg.pipeline_staging_properties import PipelineStagingManager
from .forms import CustomerSignUpForm, CustomerSignInForm, AdminSignInForm
from .models import Customer, Admin, Stage, CustServiceStage, ITStage, SalesStage, RDStage
def HomePageMethod(request):
    """Home Page for Pipeline Staging Sales Management System"""
    context = {'form': CustomerSignUpForm()}
    return render(request, 'SalesManagementSystemApp/Home.html',context)
def AboutPageMethod(request):
    """About Page for Pipeline Staging Sales Management System"""
    template_about = loader.get_template('SalesManagementSystemApp/About.html')
    context = {'template_about':template_about}
    return HttpResponse(template_about.render(context, request))
def AdminPageMethod(request):
    """Bringing up the Admin Page for necessary changes"""
    admin_page = Admin.objects.all(username=username)# pylint: disable=E0602
    return render(request, 'SalesManagementSystemApp/Admin.html',
    {'form': admin_page})
def CustomerSignIn(request):
    """Sign In Page for Pipeline Staging Sales Management System"""
    if request.method == "POST":
        customersigninform = CustomerSignInForm(request.POST)
        if customersigninform.is_valid():
            username = customersigninform.cleaned_data['username']
            password = customersigninform.cleaned_data['password']
            try:
                customercheck = Customer.objects.get(username=username)
                if customercheck.password1 == password:
                    return redirect('SalesManagementSystemApp:KeyPriorities',
                    username=username, company_name=customercheck.company_name)
                else:
                    error_message = "Invalid username or password."
            except ObjectDoesNotExist:
                error_message = "Customer does not exist. Please check your username."
            return render(request, "SalesManagementSystemApp/SignIn.html",
            {'form': customersigninform, 'error_message': error_message})
    else:
        customersigninform = CustomerSignInForm()
    return render(request, "SalesManagementSystemApp/SignIn.html",
    {'form': customersigninform})
def CustomerSignUp(request):
    """Sign Up Page for Pipeline Staging Sales Management System"""
    if request.method == "POST":
        customersignupform = CustomerSignUpForm(request.POST)
        if customersignupform.is_valid():
            customersignupform.save()
            username = customersignupform.cleaned_data.get('username')
            company_name = customersignupform.cleaned_data.get('company_name')
            return redirect('SalesManagementSystemApp:KeyPriorities',
            username=username, company_name=company_name)
        else:
            messages.error(request, "There was an error signing up")
            return redirect('SalesManagementSystemApp:Home')
    elif request.method == "GET":
        customersignupform = CustomerSignUpForm()
    return render(request,"SalesManagementSystemApp/Home.html",
    {'form':customersignupform})
def CustomerSignOut(request):
    """Sign Out Page for Pipeline Staging Sales Management System"""
    template_usersignout = loader.get_template('SalesManagementSystemApp/SignOut.html')
    context = {'template_usersignout':template_usersignout}
    return HttpResponse(template_usersignout.render(context, request))
def KeyPrioritiesMethod(request, username, company_name):
    """Key Priorities Page for Pipeline Staging Sales Management System"""
    return render(request, "SalesManagementSystemApp/KeyPriorities.html",
    {'username':username,'company_name':company_name})
def HRMethod(request, username, company_name):
    """HR Page for Pipeline Staging Sales Management System"""
    data = Stage.objects.all()
    context = {'data': data,'username': username,'company_name':company_name}
    return render(request, "SalesManagementSystemApp/HR.html", context)
def HRTableInsertStage(request, username, company_name):
    """Method for Adding Custom Stage"""
    if request.method == "POST":
        custom_stage = request.POST.get('custom_stage')
        query = Stage(custom_stage=custom_stage)
        query.save()
        messages.info(request, "Stage inserted successfully")
        stage_manager = PipelineStagingManager(bucket_name='x23203595pipelinestagingbucket')
        stage_manager.add_stage(custom_stage)
        return redirect('SalesManagementSystemApp:HR',
        username=username, company_name=company_name)
    return render(request, 'SalesManagementSystemApp/HR.html',
    {'username':username, 'company_name':company_name})
def HRTableUpdateStage(request, username, company_name, id):
    """Method for Updating Custom Stage"""
    if request.method == "POST":
        custom_stage = request.POST['custom_stage']
        update = Stage.objects.get(id=id)
        update.custom_stage = custom_stage
        update.save()
        messages.warning(request, "Stage updated successfully")
        return redirect('SalesManagementSystemApp:HR',username=username,
        company_name=company_name)
    d = Stage.objects.get(id=id)
    context = {'d': d, 'username': username, 'company_name': company_name}
    return render(request, 'SalesManagementSystemApp/HRUpdate.html', context)
def HRTableDeleteStage(request, id, stage_name, username, company_name):
    """Method for Deleting Custom Stage"""
    stage_manager = PipelineStagingManager(bucket_name='x23203595pipelinestagingbucket')
    stage_manager.delete_stage(stage_name)
    try:
        stage = Stage.objects.get(id=id)
        stage.delete()
        messages.success(request, "Stage deleted successfully")
    except Stage.DoesNotExist:
        messages.error(request, "Stage not found")
    return redirect('SalesManagementSystemApp:HR',username=username,
    company_name=company_name)
def HRTableGenerate_PDF(request, username, company_name):
    """PDF for HR Report"""
    data = Stage.objects.all()
    template_path = 'SalesManagementSystemApp/HRReport.html'
    context = {'data': data, 'username': username, 'company_name': company_name}
    template = get_template(template_path)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="HRTableReport.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('PDF generation error')
    return response
def CustServiceMethod(request, username, company_name):
    """Customer Service Page for Pipeline Staging Sales Management System"""
    data = CustServiceStage.objects.all()
    context = {'data': data, 'username': username, 'company_name': company_name}
    return render(request, "SalesManagementSystemApp/CustService.html", context)
def CustServiceTableInsertStage(request, username, company_name):
    """Method for Adding Custom Stage"""
    if request.method == "POST":
        custom_stage = request.POST.get('custom_stage')
        query = CustServiceStage(custom_stage=custom_stage)
        query.save()
        messages.info(request, "Stage inserted successfully")
        stage_manager = PipelineStagingManager(bucket_name='x23203595pipelinestagingbucket')
        stage_manager.add_stage(custom_stage)
        return redirect('SalesManagementSystemApp:CustService',
        username=username,company_name=company_name)
    return render(request, 'SalesManagementSystemApp/CustService.html',
    {'username':username,'company_name':company_name})
def CustServiceTableUpdateStage(request, username, company_name, id):
    """Method for Updating Custom Stage"""
    if request.method == "POST":
        custom_stage = request.POST['custom_stage']
        update = CustServiceStage.objects.get(id=id)
        update.custom_stage = custom_stage
        update.save()
        messages.warning(request, "Stage updated successfully")
        return redirect('SalesManagementSystemApp:CustService',
        username=username,company_name=company_name)
    d = CustServiceStage.objects.get(id=id)
    context = {'d':d,'username':username,'company_name':company_name}
    return render(request, 'SalesManagementSystemApp/CustServiceUpdate.html',
    context)
def CustServiceTableDeleteStage(request, id, stage_name, username, company_name):
    """Method for Deleting Custom Stage"""
    stage_manager = PipelineStagingManager(bucket_name='x23203595pipelinestagingbucket')
    stage_manager.delete_stage(stage_name)
    try:
        stage = CustServiceStage.objects.get(id=id)
        stage.delete()
        messages.success(request, "Stage deleted successfully")
    except CustServiceStage.DoesNotExist:
        messages.error(request, "Stage not found")
    return redirect('SalesManagementSystemApp:CustService',
    username=username,company_name=company_name)
def CustServiceTableGenerate_PDF(request, username, company_name):
    """PDF Report For Cust Service """
    data = CustServiceStage.objects.all()
    template_path = 'SalesManagementSystemApp/CustServiceReport.html'
    context = {'data': data, 'username': username, 'company_name': company_name}
    template = get_template(template_path)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="CustServiceTableReport.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('PDF generation error')
    return response
def ITMethod(request, username, company_name):
    """IT Page for Pipeline Staging Sales Management System"""

SalesManagementSystemApp/templates/SalesManagementSystemApp/HR.html
{% load static %} 
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Pipeline Staging Sales Management System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'SalesManagementSystemApp/css/newhrstyles.css' %}">
    <style>
        .fixed-container {
    position: fixed;
    top: 210px; 
    left: 50%; 
    transform: translateX(-50%);
    z-index: 1000; 
}
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-flex-start">
            <ul class="navbar-nav">
                 <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'SalesManagementSystemApp:About'%}">About</a>
                </li>
            </ul>
        </div>
        <nav class="navbar-brand">Pipeline Staging Sales Management System</nav>
         <div class="collapse navbar-collapse justify-content-end">
             <ul class="navbar-nav">
               <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'SalesManagementSystemApp:SignOut'%}">Sign Out</a>
                </li>
                </ul>
        </div>
    </div>
  </nav>

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">
            <div class="form-headingdetail">
                <h2>Key Priorities</h2>
            </div>

            <div class="tableusers">
                <table border="2">
                    <thead></thead>
                    <tbody>
                        <tr>
                            <td><b>Username:</b></td>
                            <td><b>{{ username }}</b></td>
                        </tr>
                        <tr>
                            <td><b>Company Name:</b></td>
                            <td><b>{{ company_name }}</b></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="col-md-8">
    <h2 class="text-center text-white bg-dark p-3">Stage Details</h2>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <table class="table" border = "2">
        <thead>
            <tr>
                <th scope="col">Key Priority: Charles Harris</th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
                <tr>
                    <td>{{ d.custom_stage }}</td>
                    <td><a type="button" href="{% url 'SalesManagementSystemApp:HRTableUpdateStage' id=d.id username=username company_name=company_name  %}" class="btn btn-outline-primary">Edit</a></td>
                    <td><a type="button" href="{% url 'SalesManagementSystemApp:HRTableDeleteStage' id=d.id username=username company_name=company_name stage_name=d.custom_stage %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="fixed-container">
    <div class="container mt-1">
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-center text-white bg-dark p-3">Insert Stage Details</h2>
                <form action="{% url 'SalesManagementSystemApp:HRTableInsertStage' username=username company_name=company_name %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Stage Name" name="custom_stage">
                    </div>
                    <div class="d-grid gap-2">
                        <button class="btn btn-success" type="submit">Submit</button>
                    </div>
                </form>
                <div class="d-grid gap-2">
                    <a href="{% url 'SalesManagementSystemApp:HRTableGenerate_PDF' username=username company_name=company_name %}" class="btn btn-primary">Generate PDF Report</a>
                </div>
            </div>
        </div>
    </div>
</div>
        
 {% endblock content %}
<footer class="bg-dark text-white text-center text-lg-start fixed-bottom">
  <div class="container-fluid p-3 row justify-content-center">
    <div class="row">
     <div class="text-center">
       © Copyright: Pipeline Staging Sales Management System
     </div>
    </div>
  </div>
</footer>
  </body>
</html>

SalesManagementSystemApp/templates/SalesManagementSystemApp/IT.html
{% load static %} 
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Pipeline Staging Sales Management System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'SalesManagementSystemApp/css/newitstyles.css' %}">
    <style>
        .fixed-container {
    position: fixed;
    top: 210px; 
    left: 50%; 
    transform: translateX(-50%);
    z-index: 1000; 
}
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-flex-start">
            <ul class="navbar-nav">
                 <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'SalesManagementSystemApp:About'%}">About</a>
                </li>
            </ul>
        </div>
        <nav class="navbar-brand">Pipeline Staging Sales Management System</nav>
         <div class="collapse navbar-collapse justify-content-end">
             <ul class="navbar-nav">
               <li class="nav-item">
                    <a class="nav-link" 
                href="{%url 'SalesManagementSystemApp:SignOut'%}">Sign Out</a>
                </li>
                </ul>
        </div>
    </div>
  </nav>

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">
            <div class="form-headingdetail">
                <h2>Key Priorities</h2>
            </div>

            <div class="tableusers">
                <table border="2">
                    <thead></thead>
                    <tbody>
                        <tr>
                            <td><b>Username:</b></td>
                            <td><b>{{ username }}</b></td>
                        </tr>
                        <tr>
                            <td><b>Company Name:</b></td>
                            <td><b>{{ company_name }}</b></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="col-md-8">
    <h2 class="text-center text-white bg-dark p-3">Stage Details</h2>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}


    <table class="table" border = "2">
        <thead>
            <tr>
                <th scope="col">Key Priority: Algie Rivers</th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
                <tr>
                    <td>{{ d.custom_stage }}</td>
                    <td><a type="button" href="{% url 'SalesManagementSystemApp:ITTableUpdateStage' id=d.id username=username company_name=company_name  %}" class="btn btn-outline-primary">Edit</a></td>
                    <td><a type="button" href="{% url 'SalesManagementSystemApp:ITTableDeleteStage' id=d.id username=username company_name=company_name stage_name=d.custom_stage %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="fixed-container">
    <div class="container mt-1">
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-center text-white bg-dark p-3">Insert Stage Details</h2>
                <form action="{% url 'SalesManagementSystemApp:ITTableInsertStage' username=username company_name=company_name %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Stage Name" name="custom_stage">
                    </div>
                    <div class="d-grid gap-2">
                        <button class="btn btn-success" type="submit">Submit</button>
                    </div>
                </form>
                <div class="d-grid gap-2">
                    <a href="{% url 'SalesManagementSystemApp:ITTableGenerate_PDF' username=username company_name=company_name %}" class="btn btn-primary">Generate PDF Report</a>
                </div>
            </div>
        </div>
    </div>
</div>

 {% endblock content %}
 
<footer class="bg-dark text-white text-center text-lg-start fixed-bottom">
  <div class="container-fluid p-3 row justify-content-center">
    <div class="row">
     <div class="text-center">
       © Copyright: Pipeline Staging Sales Management System
     </div>
    </div>
  </div>
</footer>
  </body>
</html>